# Generated by Django 5.0.1 on 2024-01-12 02:18

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_alter_contract_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=contracts.models.contract_file
            ),
        ),
    ]
