# Generated by Django 5.0.1 on 2024-01-13 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0004_alter_contract_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="uniq_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
