# Generated by Django 5.0.1 on 2024-01-13 05:26
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("contracts", "Contract")
    for row in MyModel.objects.all():
        row.uniq_id = uuid.uuid4()
        row.save(update_fields=["uniq_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_contract_uniq_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
