# Generated by Django 5.0.1 on 2024-01-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, null=True)),
                ("second_name", models.CharField(max_length=50, null=True)),
                ("surname", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone",
                    models.CharField(default="+0123456789", max_length=12, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="example@mail.com", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("POTENTIAL", "Потенциальный"),
                            ("ACTIVE", "Активный"),
                            ("INACTIVE", "Неактивный"),
                        ],
                        default="POTENTIAL",
                        max_length=20,
                    ),
                ),
                (
                    "ads",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads.ads",
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
